version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: gzg_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev_user -d gzg_dev" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gzg_network

  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./auth/uploads:/app/uploads
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev_user -d gzg_dev" ]
      interval: 5s
      retries: 5
    networks:
      - gzg_network

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: gzg_git_swagger_ui
    ports:
      - "8080:8080"
    volumes:
      - ./openapi.yaml:/usr/share/nginx/html/openapi.yaml
    environment:
      API_URL: openapi.yaml
    networks:
      - gzg_network

volumes:
  postgres_data: 

networks:
  gzg_network:
    driver: bridge