services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: gzg_git_swagger_ui
    ports:
      - "8080:8080"
    volumes:
      - ./openapi.yaml:/usr/share/nginx/html/openapi.yaml
    environment:
      API_URL: openapi.yaml